//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.WsKormerciProd {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ecommerce.redecard.com.br", ConfigurationName="WsKormerciProd.komerci_captureSoap")]
    public interface komerci_captureSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ecommerce.redecard.com.br/VoidPreAuthorization", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode VoidPreAuthorization(string Filiacao, string Distribuidor, string Total, string Data, string NumAutor, string NumCV, string Concentrador, string Usr, string Pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ecommerce.redecard.com.br/VoidDebtTransaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode VoidDebtTransaction(string Total, string Filiacao, string NumCV, string NumAutor, string Concentrador, string Usr, string Pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ecommerce.redecard.com.br/VoidTransaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode VoidTransaction(string Total, string Filiacao, string NumCV, string NumAutor, string Concentrador, string Usr, string Pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ecommerce.redecard.com.br/VoidTransactionDistr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode VoidTransactionDistr(string Total, string Filiacao, string Data, string NumCV, string NumAutor, string Concentrador, string Distribuidor, string Usr, string Pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ecommerce.redecard.com.br/VoidConfPreAuthorization", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode VoidConfPreAuthorization(string Filiacao, string Total, string Data, string NumAutor, string NumCV, string Concentrador, string Usr, string Pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ecommerce.redecard.com.br/GetAuthorized_AD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetAuthorized_AD(
                    string Total, 
                    string Transacao, 
                    string Parcelas, 
                    string Filiacao, 
                    string NumPedido, 
                    string Nrcartao, 
                    string CVC2, 
                    string Mes, 
                    string Ano, 
                    string Portador, 
                    string IATA, 
                    string Distribuidor, 
                    string Concentrador, 
                    string TaxaEmbarque, 
                    string Entrada, 
                    string Pax1, 
                    string Pax2, 
                    string Pax3, 
                    string Pax4, 
                    string Numdoc1, 
                    string Numdoc2, 
                    string Numdoc3, 
                    string Numdoc4, 
                    string Add_Data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ecommerce.redecard.com.br/GetAuthorized", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetAuthorized(
                    string Total, 
                    string Transacao, 
                    string Parcelas, 
                    string Filiacao, 
                    string NumPedido, 
                    string Nrcartao, 
                    string CVC2, 
                    string Mes, 
                    string Ano, 
                    string Portador, 
                    string IATA, 
                    string Distribuidor, 
                    string Concentrador, 
                    string TaxaEmbarque, 
                    string Entrada, 
                    string Pax1, 
                    string Pax2, 
                    string Pax3, 
                    string Pax4, 
                    string Numdoc1, 
                    string Numdoc2, 
                    string Numdoc3, 
                    string Numdoc4, 
                    string ConfTxn, 
                    string Add_Data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ecommerce.redecard.com.br/GetAuthorizedAVS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetAuthorizedAVS(
                    string Total, 
                    string Transacao, 
                    string Parcelas, 
                    string Filiacao, 
                    string NumPedido, 
                    string Nrcartao, 
                    string CVC2, 
                    string Mes, 
                    string Ano, 
                    string Portador, 
                    string CPF, 
                    string Endereco, 
                    string Num1, 
                    string Complemento, 
                    string Cep1, 
                    string Cep2, 
                    string IATA, 
                    string Distribuidor, 
                    string Concentrador, 
                    string TaxaEmbarque, 
                    string Entrada, 
                    string Pax1, 
                    string Pax2, 
                    string Pax3, 
                    string Pax4, 
                    string Numdoc1, 
                    string Numdoc2, 
                    string Numdoc3, 
                    string Numdoc4);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ecommerce.redecard.com.br/ReversalTxn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ReversalTxn(string Filiacao, string Distribuidor, string Total, string Data, string NumAutor, string NumSqn, string NumPedido, string Parcelas, string Usr, string Pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ecommerce.redecard.com.br/SalesSumm", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode SalesSumm(string Filiacao, string Usr, string Pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ecommerce.redecard.com.br/ConfirmTxn_AD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ConfirmTxn_AD(
                    string Data, 
                    string NumSqn, 
                    string NumCV, 
                    string NumAutor, 
                    string Parcelas, 
                    string TransOrig, 
                    string Total, 
                    string Filiacao, 
                    string Distribuidor, 
                    string NumPedido, 
                    string Pax1, 
                    string Pax2, 
                    string Pax3, 
                    string Pax4, 
                    string Numdoc1, 
                    string Numdoc2, 
                    string Numdoc3, 
                    string Numdoc4, 
                    string Cod_Banco, 
                    string Origem_Bin, 
                    string AddData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ecommerce.redecard.com.br/ConfirmTxn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ConfirmTxn(
                    string Data, 
                    string NumSqn, 
                    string NumCV, 
                    string NumAutor, 
                    string Parcelas, 
                    string TransOrig, 
                    string Total, 
                    string Filiacao, 
                    string Distribuidor, 
                    string NumPedido, 
                    string Pax1, 
                    string Pax2, 
                    string Pax3, 
                    string Pax4, 
                    string Numdoc1, 
                    string Numdoc2, 
                    string Numdoc3, 
                    string Numdoc4, 
                    string AddData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ecommerce.redecard.com.br/CouncilReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode CouncilReport(string Filiacao, string Distribuidor, string Data_Inicial, string Data_Final, string Tipo_Trx, string Status_Trx, string Servico_AVS, string Programa, string Usr, string Pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ecommerce.redecard.com.br/ConfPreAuthorization", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ConfPreAuthorization(string Filiacao, string Distribuidor, string Total, string Parcelas, string Data, string NumAutor, string NumCV, string Concentrador, string Usr, string Pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ecommerce.redecard.com.br/ConsFornDistrib", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ConsFornDistrib(string Filiacao, string Usr, string Pwd);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface komerci_captureSoapChannel : BLL.WsKormerciProd.komerci_captureSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class komerci_captureSoapClient : System.ServiceModel.ClientBase<BLL.WsKormerciProd.komerci_captureSoap>, BLL.WsKormerciProd.komerci_captureSoap {
        
        public komerci_captureSoapClient() {
        }
        
        public komerci_captureSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public komerci_captureSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public komerci_captureSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public komerci_captureSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Xml.XmlNode VoidPreAuthorization(string Filiacao, string Distribuidor, string Total, string Data, string NumAutor, string NumCV, string Concentrador, string Usr, string Pwd) {
            return base.Channel.VoidPreAuthorization(Filiacao, Distribuidor, Total, Data, NumAutor, NumCV, Concentrador, Usr, Pwd);
        }
        
        public System.Xml.XmlNode VoidDebtTransaction(string Total, string Filiacao, string NumCV, string NumAutor, string Concentrador, string Usr, string Pwd) {
            return base.Channel.VoidDebtTransaction(Total, Filiacao, NumCV, NumAutor, Concentrador, Usr, Pwd);
        }
        
        public System.Xml.XmlNode VoidTransaction(string Total, string Filiacao, string NumCV, string NumAutor, string Concentrador, string Usr, string Pwd) {
            return base.Channel.VoidTransaction(Total, Filiacao, NumCV, NumAutor, Concentrador, Usr, Pwd);
        }
        
        public System.Xml.XmlNode VoidTransactionDistr(string Total, string Filiacao, string Data, string NumCV, string NumAutor, string Concentrador, string Distribuidor, string Usr, string Pwd) {
            return base.Channel.VoidTransactionDistr(Total, Filiacao, Data, NumCV, NumAutor, Concentrador, Distribuidor, Usr, Pwd);
        }
        
        public System.Xml.XmlNode VoidConfPreAuthorization(string Filiacao, string Total, string Data, string NumAutor, string NumCV, string Concentrador, string Usr, string Pwd) {
            return base.Channel.VoidConfPreAuthorization(Filiacao, Total, Data, NumAutor, NumCV, Concentrador, Usr, Pwd);
        }
        
        public System.Xml.XmlNode GetAuthorized_AD(
                    string Total, 
                    string Transacao, 
                    string Parcelas, 
                    string Filiacao, 
                    string NumPedido, 
                    string Nrcartao, 
                    string CVC2, 
                    string Mes, 
                    string Ano, 
                    string Portador, 
                    string IATA, 
                    string Distribuidor, 
                    string Concentrador, 
                    string TaxaEmbarque, 
                    string Entrada, 
                    string Pax1, 
                    string Pax2, 
                    string Pax3, 
                    string Pax4, 
                    string Numdoc1, 
                    string Numdoc2, 
                    string Numdoc3, 
                    string Numdoc4, 
                    string Add_Data) {
            return base.Channel.GetAuthorized_AD(Total, Transacao, Parcelas, Filiacao, NumPedido, Nrcartao, CVC2, Mes, Ano, Portador, IATA, Distribuidor, Concentrador, TaxaEmbarque, Entrada, Pax1, Pax2, Pax3, Pax4, Numdoc1, Numdoc2, Numdoc3, Numdoc4, Add_Data);
        }
        
        public System.Xml.XmlNode GetAuthorized(
                    string Total, 
                    string Transacao, 
                    string Parcelas, 
                    string Filiacao, 
                    string NumPedido, 
                    string Nrcartao, 
                    string CVC2, 
                    string Mes, 
                    string Ano, 
                    string Portador, 
                    string IATA, 
                    string Distribuidor, 
                    string Concentrador, 
                    string TaxaEmbarque, 
                    string Entrada, 
                    string Pax1, 
                    string Pax2, 
                    string Pax3, 
                    string Pax4, 
                    string Numdoc1, 
                    string Numdoc2, 
                    string Numdoc3, 
                    string Numdoc4, 
                    string ConfTxn, 
                    string Add_Data) {
            return base.Channel.GetAuthorized(Total, Transacao, Parcelas, Filiacao, NumPedido, Nrcartao, CVC2, Mes, Ano, Portador, IATA, Distribuidor, Concentrador, TaxaEmbarque, Entrada, Pax1, Pax2, Pax3, Pax4, Numdoc1, Numdoc2, Numdoc3, Numdoc4, ConfTxn, Add_Data);
        }
        
        public System.Xml.XmlNode GetAuthorizedAVS(
                    string Total, 
                    string Transacao, 
                    string Parcelas, 
                    string Filiacao, 
                    string NumPedido, 
                    string Nrcartao, 
                    string CVC2, 
                    string Mes, 
                    string Ano, 
                    string Portador, 
                    string CPF, 
                    string Endereco, 
                    string Num1, 
                    string Complemento, 
                    string Cep1, 
                    string Cep2, 
                    string IATA, 
                    string Distribuidor, 
                    string Concentrador, 
                    string TaxaEmbarque, 
                    string Entrada, 
                    string Pax1, 
                    string Pax2, 
                    string Pax3, 
                    string Pax4, 
                    string Numdoc1, 
                    string Numdoc2, 
                    string Numdoc3, 
                    string Numdoc4) {
            return base.Channel.GetAuthorizedAVS(Total, Transacao, Parcelas, Filiacao, NumPedido, Nrcartao, CVC2, Mes, Ano, Portador, CPF, Endereco, Num1, Complemento, Cep1, Cep2, IATA, Distribuidor, Concentrador, TaxaEmbarque, Entrada, Pax1, Pax2, Pax3, Pax4, Numdoc1, Numdoc2, Numdoc3, Numdoc4);
        }
        
        public System.Xml.XmlNode ReversalTxn(string Filiacao, string Distribuidor, string Total, string Data, string NumAutor, string NumSqn, string NumPedido, string Parcelas, string Usr, string Pwd) {
            return base.Channel.ReversalTxn(Filiacao, Distribuidor, Total, Data, NumAutor, NumSqn, NumPedido, Parcelas, Usr, Pwd);
        }
        
        public System.Xml.XmlNode SalesSumm(string Filiacao, string Usr, string Pwd) {
            return base.Channel.SalesSumm(Filiacao, Usr, Pwd);
        }
        
        public System.Xml.XmlNode ConfirmTxn_AD(
                    string Data, 
                    string NumSqn, 
                    string NumCV, 
                    string NumAutor, 
                    string Parcelas, 
                    string TransOrig, 
                    string Total, 
                    string Filiacao, 
                    string Distribuidor, 
                    string NumPedido, 
                    string Pax1, 
                    string Pax2, 
                    string Pax3, 
                    string Pax4, 
                    string Numdoc1, 
                    string Numdoc2, 
                    string Numdoc3, 
                    string Numdoc4, 
                    string Cod_Banco, 
                    string Origem_Bin, 
                    string AddData) {
            return base.Channel.ConfirmTxn_AD(Data, NumSqn, NumCV, NumAutor, Parcelas, TransOrig, Total, Filiacao, Distribuidor, NumPedido, Pax1, Pax2, Pax3, Pax4, Numdoc1, Numdoc2, Numdoc3, Numdoc4, Cod_Banco, Origem_Bin, AddData);
        }
        
        public System.Xml.XmlNode ConfirmTxn(
                    string Data, 
                    string NumSqn, 
                    string NumCV, 
                    string NumAutor, 
                    string Parcelas, 
                    string TransOrig, 
                    string Total, 
                    string Filiacao, 
                    string Distribuidor, 
                    string NumPedido, 
                    string Pax1, 
                    string Pax2, 
                    string Pax3, 
                    string Pax4, 
                    string Numdoc1, 
                    string Numdoc2, 
                    string Numdoc3, 
                    string Numdoc4, 
                    string AddData) {
            return base.Channel.ConfirmTxn(Data, NumSqn, NumCV, NumAutor, Parcelas, TransOrig, Total, Filiacao, Distribuidor, NumPedido, Pax1, Pax2, Pax3, Pax4, Numdoc1, Numdoc2, Numdoc3, Numdoc4, AddData);
        }
        
        public System.Xml.XmlNode CouncilReport(string Filiacao, string Distribuidor, string Data_Inicial, string Data_Final, string Tipo_Trx, string Status_Trx, string Servico_AVS, string Programa, string Usr, string Pwd) {
            return base.Channel.CouncilReport(Filiacao, Distribuidor, Data_Inicial, Data_Final, Tipo_Trx, Status_Trx, Servico_AVS, Programa, Usr, Pwd);
        }
        
        public System.Xml.XmlNode ConfPreAuthorization(string Filiacao, string Distribuidor, string Total, string Parcelas, string Data, string NumAutor, string NumCV, string Concentrador, string Usr, string Pwd) {
            return base.Channel.ConfPreAuthorization(Filiacao, Distribuidor, Total, Parcelas, Data, NumAutor, NumCV, Concentrador, Usr, Pwd);
        }
        
        public System.Xml.XmlNode ConsFornDistrib(string Filiacao, string Usr, string Pwd) {
            return base.Channel.ConsFornDistrib(Filiacao, Usr, Pwd);
        }
    }
}
