//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.DBI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:DBIwsIntf-IDBIws", ConfigurationName="DBI.IDBIws")]
    public interface IDBIws {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:DBIwsIntf-IDBIws#ConsultaOnLine", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string ConsultaOnLine(string usuario, string senha, int CodigoConsulta, string Valor1, string Valor2, string Valor3, string Valor4, string Valor5);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:DBIwsIntf-IDBIws#VerificaDisponibilidade", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string VerificaDisponibilidade(string usuario, string senha, int CodigoConsulta);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:DBIwsIntf-IDBIws#CheckOnLine", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        int CheckOnLine();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDBIwsChannel : BLL.DBI.IDBIws, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DBIwsClient : System.ServiceModel.ClientBase<BLL.DBI.IDBIws>, BLL.DBI.IDBIws {
        
        public DBIwsClient() {
        }
        
        public DBIwsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DBIwsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBIwsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBIwsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ConsultaOnLine(string usuario, string senha, int CodigoConsulta, string Valor1, string Valor2, string Valor3, string Valor4, string Valor5) {
            return base.Channel.ConsultaOnLine(usuario, senha, CodigoConsulta, Valor1, Valor2, Valor3, Valor4, Valor5);
        }
        
        public string VerificaDisponibilidade(string usuario, string senha, int CodigoConsulta) {
            return base.Channel.VerificaDisponibilidade(usuario, senha, CodigoConsulta);
        }
        
        public int CheckOnLine() {
            return base.Channel.CheckOnLine();
        }
    }
}
