//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.ServiceOP {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetornoWSBase", Namespace="http://schemas.datacontract.org/2004/07/OP.DTO.ClassesContrato")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BLL.ServiceOP.RetornoEmitirBoleto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BLL.ServiceOP.RetornoEstornoConfirmacaoCredito))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BLL.ServiceOP.RetornoEmitirAutorizacaoCartaoCredito))]
    public partial class RetornoWSBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetornoEmitirBoleto", Namespace="http://schemas.datacontract.org/2004/07/OP.DTO.ClassesContrato")]
    [System.SerializableAttribute()]
    public partial class RetornoEmitirBoleto : BLL.ServiceOP.RetornoWSBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodRetornoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetalheMensagemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensagemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumPedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PagamentoBoletoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusPagamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLImpressaoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodRetorno {
            get {
                return this.CodRetornoField;
            }
            set {
                if ((this.CodRetornoField.Equals(value) != true)) {
                    this.CodRetornoField = value;
                    this.RaisePropertyChanged("CodRetorno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DetalheMensagem {
            get {
                return this.DetalheMensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.DetalheMensagemField, value) != true)) {
                    this.DetalheMensagemField = value;
                    this.RaisePropertyChanged("DetalheMensagem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensagem {
            get {
                return this.MensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemField, value) != true)) {
                    this.MensagemField = value;
                    this.RaisePropertyChanged("Mensagem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumPedido {
            get {
                return this.NumPedidoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumPedidoField, value) != true)) {
                    this.NumPedidoField = value;
                    this.RaisePropertyChanged("NumPedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PagamentoBoletoId {
            get {
                return this.PagamentoBoletoIdField;
            }
            set {
                if ((this.PagamentoBoletoIdField.Equals(value) != true)) {
                    this.PagamentoBoletoIdField = value;
                    this.RaisePropertyChanged("PagamentoBoletoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusPagamento {
            get {
                return this.StatusPagamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusPagamentoField, value) != true)) {
                    this.StatusPagamentoField = value;
                    this.RaisePropertyChanged("StatusPagamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URLImpressao {
            get {
                return this.URLImpressaoField;
            }
            set {
                if ((object.ReferenceEquals(this.URLImpressaoField, value) != true)) {
                    this.URLImpressaoField = value;
                    this.RaisePropertyChanged("URLImpressao");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetornoEstornoConfirmacaoCredito", Namespace="http://schemas.datacontract.org/2004/07/OP.DTO.ClassesContrato")]
    [System.SerializableAttribute()]
    public partial class RetornoEstornoConfirmacaoCredito : BLL.ServiceOP.RetornoWSBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodRetornoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetalheMensagemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensagemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PagamentoCartaoCreditoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusPagamentoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodRetorno {
            get {
                return this.CodRetornoField;
            }
            set {
                if ((this.CodRetornoField.Equals(value) != true)) {
                    this.CodRetornoField = value;
                    this.RaisePropertyChanged("CodRetorno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DetalheMensagem {
            get {
                return this.DetalheMensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.DetalheMensagemField, value) != true)) {
                    this.DetalheMensagemField = value;
                    this.RaisePropertyChanged("DetalheMensagem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensagem {
            get {
                return this.MensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemField, value) != true)) {
                    this.MensagemField = value;
                    this.RaisePropertyChanged("Mensagem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PagamentoCartaoCreditoId {
            get {
                return this.PagamentoCartaoCreditoIdField;
            }
            set {
                if ((this.PagamentoCartaoCreditoIdField.Equals(value) != true)) {
                    this.PagamentoCartaoCreditoIdField = value;
                    this.RaisePropertyChanged("PagamentoCartaoCreditoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pedido {
            get {
                return this.PedidoField;
            }
            set {
                if ((object.ReferenceEquals(this.PedidoField, value) != true)) {
                    this.PedidoField = value;
                    this.RaisePropertyChanged("Pedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusPagamento {
            get {
                return this.StatusPagamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusPagamentoField, value) != true)) {
                    this.StatusPagamentoField = value;
                    this.RaisePropertyChanged("StatusPagamento");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetornoEmitirAutorizacaoCartaoCredito", Namespace="http://schemas.datacontract.org/2004/07/OP.DTO.ClassesContrato")]
    [System.SerializableAttribute()]
    public partial class RetornoEmitirAutorizacaoCartaoCredito : BLL.ServiceOP.RetornoWSBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodRetornoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetalheMensagemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensagemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PagamentoCartaoCreditoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusPagamentoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodRetorno {
            get {
                return this.CodRetornoField;
            }
            set {
                if ((this.CodRetornoField.Equals(value) != true)) {
                    this.CodRetornoField = value;
                    this.RaisePropertyChanged("CodRetorno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DetalheMensagem {
            get {
                return this.DetalheMensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.DetalheMensagemField, value) != true)) {
                    this.DetalheMensagemField = value;
                    this.RaisePropertyChanged("DetalheMensagem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensagem {
            get {
                return this.MensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemField, value) != true)) {
                    this.MensagemField = value;
                    this.RaisePropertyChanged("Mensagem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PagamentoCartaoCreditoId {
            get {
                return this.PagamentoCartaoCreditoIdField;
            }
            set {
                if ((this.PagamentoCartaoCreditoIdField.Equals(value) != true)) {
                    this.PagamentoCartaoCreditoIdField = value;
                    this.RaisePropertyChanged("PagamentoCartaoCreditoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pedido {
            get {
                return this.PedidoField;
            }
            set {
                if ((object.ReferenceEquals(this.PedidoField, value) != true)) {
                    this.PedidoField = value;
                    this.RaisePropertyChanged("Pedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusPagamento {
            get {
                return this.StatusPagamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusPagamentoField, value) != true)) {
                    this.StatusPagamentoField = value;
                    this.RaisePropertyChanged("StatusPagamento");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceOP.IServiceOP")]
    public interface IServiceOP {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOP/EmitirAutorizacaoCartaoCredito", ReplyAction="http://tempuri.org/IServiceOP/EmitirAutorizacaoCartaoCreditoResponse")]
        BLL.ServiceOP.RetornoEmitirAutorizacaoCartaoCredito EmitirAutorizacaoCartaoCredito(
                    string aplicacaoSolicitante, 
                    string numPedido, 
                    System.DateTime dataPedido, 
                    decimal valorTotal, 
                    int numParcelas, 
                    string numCartao, 
                    string cvc2, 
                    int mes, 
                    int ano, 
                    string portador, 
                    string nomeCliente, 
                    string cpfCliente, 
                    string ruaCliente, 
                    string bairroCliente, 
                    string cidadeCliente, 
                    string ufCliente, 
                    string cepCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOP/EmitirBoleto", ReplyAction="http://tempuri.org/IServiceOP/EmitirBoletoResponse")]
        BLL.ServiceOP.RetornoEmitirBoleto EmitirBoleto(
                    string AplicacaoSolicitante, 
                    string NumPedido, 
                    System.DateTime DataPedido, 
                    decimal ValorBoleto, 
                    System.DateTime VencimentoBoleto, 
                    System.Nullable<decimal> DescontoAntecipacao, 
                    System.Nullable<System.DateTime> DataAntecipacao, 
                    System.Nullable<decimal> Juros, 
                    System.Nullable<decimal> Multa, 
                    string NomeSacado, 
                    string CPFSacado, 
                    string RuaSacado, 
                    string BairroSacado, 
                    string CidadeSacado, 
                    string UFSacado, 
                    string CEPSacado, 
                    string Instrucoes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOP/EstornoConfirmacaoCredito", ReplyAction="http://tempuri.org/IServiceOP/EstornoConfirmacaoCreditoResponse")]
        BLL.ServiceOP.RetornoEstornoConfirmacaoCredito EstornoConfirmacaoCredito(string aplicacaoSolicitante, int pagamentoCartaoCreditoid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceOPChannel : BLL.ServiceOP.IServiceOP, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceOPClient : System.ServiceModel.ClientBase<BLL.ServiceOP.IServiceOP>, BLL.ServiceOP.IServiceOP {
        
        public ServiceOPClient() {
        }
        
        public ServiceOPClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceOPClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOPClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOPClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BLL.ServiceOP.RetornoEmitirAutorizacaoCartaoCredito EmitirAutorizacaoCartaoCredito(
                    string aplicacaoSolicitante, 
                    string numPedido, 
                    System.DateTime dataPedido, 
                    decimal valorTotal, 
                    int numParcelas, 
                    string numCartao, 
                    string cvc2, 
                    int mes, 
                    int ano, 
                    string portador, 
                    string nomeCliente, 
                    string cpfCliente, 
                    string ruaCliente, 
                    string bairroCliente, 
                    string cidadeCliente, 
                    string ufCliente, 
                    string cepCliente) {
            return base.Channel.EmitirAutorizacaoCartaoCredito(aplicacaoSolicitante, numPedido, dataPedido, valorTotal, numParcelas, numCartao, cvc2, mes, ano, portador, nomeCliente, cpfCliente, ruaCliente, bairroCliente, cidadeCliente, ufCliente, cepCliente);
        }
        
        public BLL.ServiceOP.RetornoEmitirBoleto EmitirBoleto(
                    string AplicacaoSolicitante, 
                    string NumPedido, 
                    System.DateTime DataPedido, 
                    decimal ValorBoleto, 
                    System.DateTime VencimentoBoleto, 
                    System.Nullable<decimal> DescontoAntecipacao, 
                    System.Nullable<System.DateTime> DataAntecipacao, 
                    System.Nullable<decimal> Juros, 
                    System.Nullable<decimal> Multa, 
                    string NomeSacado, 
                    string CPFSacado, 
                    string RuaSacado, 
                    string BairroSacado, 
                    string CidadeSacado, 
                    string UFSacado, 
                    string CEPSacado, 
                    string Instrucoes) {
            return base.Channel.EmitirBoleto(AplicacaoSolicitante, NumPedido, DataPedido, ValorBoleto, VencimentoBoleto, DescontoAntecipacao, DataAntecipacao, Juros, Multa, NomeSacado, CPFSacado, RuaSacado, BairroSacado, CidadeSacado, UFSacado, CEPSacado, Instrucoes);
        }
        
        public BLL.ServiceOP.RetornoEstornoConfirmacaoCredito EstornoConfirmacaoCredito(string aplicacaoSolicitante, int pagamentoCartaoCreditoid) {
            return base.Channel.EstornoConfirmacaoCredito(aplicacaoSolicitante, pagamentoCartaoCreditoid);
        }
    }
}
