//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.WsKormerciTeste {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ecommerce.redecard.com.br", ConfigurationName="WsKormerciTeste.komerci_capture_testeSoap")]
    public interface komerci_capture_testeSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ecommerce.redecard.com.br/ConfirmTxnTst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ConfirmTxnTst(
                    string Data, 
                    string NumSqn, 
                    string NumCV, 
                    string NumAutor, 
                    string Parcelas, 
                    string TransOrig, 
                    string Total, 
                    string Filiacao, 
                    string Distribuidor, 
                    string NumPedido, 
                    string Pax1, 
                    string Pax2, 
                    string Pax3, 
                    string Pax4, 
                    string Numdoc1, 
                    string Numdoc2, 
                    string Numdoc3, 
                    string Numdoc4, 
                    string AddData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ecommerce.redecard.com.br/SalesSummTst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode SalesSummTst(string Filiacao, string Usr, string Pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ecommerce.redecard.com.br/CouncilReportTst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode CouncilReportTst(string Filiacao, string Distribuidor, string Data_Inicial, string Data_Final, string Tipo_Trx, string Status_Trx, string Servico_AVS, string Usr, string Pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ecommerce.redecard.com.br/VoidConfPreAuthorizationTst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode VoidConfPreAuthorizationTst(string Filiacao, string Distribuidor, string Total, string Data, string NumAutor, string NumCV, string Concentrador, string Usr, string Pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ecommerce.redecard.com.br/ConfPreAuthorizationTst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ConfPreAuthorizationTst(string Filiacao, string Distribuidor, string Total, string TransOrig, string Parcelas, string Data, string NumAutor, string NumCV, string Concentrador, string Usr, string Pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ecommerce.redecard.com.br/VoidPreAuthorizationTst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode VoidPreAuthorizationTst(string Filiacao, string Distribuidor, string Total, string Data, string NumAutor, string NumCV, string Concentrador, string Usr, string Pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ecommerce.redecard.com.br/VoidTransactionTst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode VoidTransactionTst(string Total, string Filiacao, string NumCV, string NumAutor, string Concentrador, string Usr, string Pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ecommerce.redecard.com.br/GetAuthorizedTst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetAuthorizedTst(
                    string Total, 
                    string Transacao, 
                    string Parcelas, 
                    string Filiacao, 
                    string NumPedido, 
                    string Nrcartao, 
                    string CVC2, 
                    string Mes, 
                    string Ano, 
                    string Portador, 
                    string IATA, 
                    string Distribuidor, 
                    string Concentrador, 
                    string TaxaEmbarque, 
                    string Entrada, 
                    string Pax1, 
                    string Pax2, 
                    string Pax3, 
                    string Pax4, 
                    string Numdoc1, 
                    string Numdoc2, 
                    string Numdoc3, 
                    string Numdoc4, 
                    string ConfTxn, 
                    string AddData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ecommerce.redecard.com.br/GetAuthorizedAVSTst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetAuthorizedAVSTst(
                    string Total, 
                    string Transacao, 
                    string Parcelas, 
                    string Filiacao, 
                    string NumPedido, 
                    string Nrcartao, 
                    string CVC2, 
                    string Mes, 
                    string Ano, 
                    string Portador, 
                    string CPF, 
                    string Endereco, 
                    string Num1, 
                    string Complemento, 
                    string Cep1, 
                    string Cep2, 
                    string IATA, 
                    string Distribuidor, 
                    string Concentrador, 
                    string TaxaEmbarque, 
                    string Entrada, 
                    string Pax1, 
                    string Pax2, 
                    string Pax3, 
                    string Pax4, 
                    string Numdoc1, 
                    string Numdoc2, 
                    string Numdoc3, 
                    string Numdoc4);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface komerci_capture_testeSoapChannel : BLL.WsKormerciTeste.komerci_capture_testeSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class komerci_capture_testeSoapClient : System.ServiceModel.ClientBase<BLL.WsKormerciTeste.komerci_capture_testeSoap>, BLL.WsKormerciTeste.komerci_capture_testeSoap {
        
        public komerci_capture_testeSoapClient() {
        }
        
        public komerci_capture_testeSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public komerci_capture_testeSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public komerci_capture_testeSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public komerci_capture_testeSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Xml.XmlNode ConfirmTxnTst(
                    string Data, 
                    string NumSqn, 
                    string NumCV, 
                    string NumAutor, 
                    string Parcelas, 
                    string TransOrig, 
                    string Total, 
                    string Filiacao, 
                    string Distribuidor, 
                    string NumPedido, 
                    string Pax1, 
                    string Pax2, 
                    string Pax3, 
                    string Pax4, 
                    string Numdoc1, 
                    string Numdoc2, 
                    string Numdoc3, 
                    string Numdoc4, 
                    string AddData) {
            return base.Channel.ConfirmTxnTst(Data, NumSqn, NumCV, NumAutor, Parcelas, TransOrig, Total, Filiacao, Distribuidor, NumPedido, Pax1, Pax2, Pax3, Pax4, Numdoc1, Numdoc2, Numdoc3, Numdoc4, AddData);
        }
        
        public System.Xml.XmlNode SalesSummTst(string Filiacao, string Usr, string Pwd) {
            return base.Channel.SalesSummTst(Filiacao, Usr, Pwd);
        }
        
        public System.Xml.XmlNode CouncilReportTst(string Filiacao, string Distribuidor, string Data_Inicial, string Data_Final, string Tipo_Trx, string Status_Trx, string Servico_AVS, string Usr, string Pwd) {
            return base.Channel.CouncilReportTst(Filiacao, Distribuidor, Data_Inicial, Data_Final, Tipo_Trx, Status_Trx, Servico_AVS, Usr, Pwd);
        }
        
        public System.Xml.XmlNode VoidConfPreAuthorizationTst(string Filiacao, string Distribuidor, string Total, string Data, string NumAutor, string NumCV, string Concentrador, string Usr, string Pwd) {
            return base.Channel.VoidConfPreAuthorizationTst(Filiacao, Distribuidor, Total, Data, NumAutor, NumCV, Concentrador, Usr, Pwd);
        }
        
        public System.Xml.XmlNode ConfPreAuthorizationTst(string Filiacao, string Distribuidor, string Total, string TransOrig, string Parcelas, string Data, string NumAutor, string NumCV, string Concentrador, string Usr, string Pwd) {
            return base.Channel.ConfPreAuthorizationTst(Filiacao, Distribuidor, Total, TransOrig, Parcelas, Data, NumAutor, NumCV, Concentrador, Usr, Pwd);
        }
        
        public System.Xml.XmlNode VoidPreAuthorizationTst(string Filiacao, string Distribuidor, string Total, string Data, string NumAutor, string NumCV, string Concentrador, string Usr, string Pwd) {
            return base.Channel.VoidPreAuthorizationTst(Filiacao, Distribuidor, Total, Data, NumAutor, NumCV, Concentrador, Usr, Pwd);
        }
        
        public System.Xml.XmlNode VoidTransactionTst(string Total, string Filiacao, string NumCV, string NumAutor, string Concentrador, string Usr, string Pwd) {
            return base.Channel.VoidTransactionTst(Total, Filiacao, NumCV, NumAutor, Concentrador, Usr, Pwd);
        }
        
        public System.Xml.XmlNode GetAuthorizedTst(
                    string Total, 
                    string Transacao, 
                    string Parcelas, 
                    string Filiacao, 
                    string NumPedido, 
                    string Nrcartao, 
                    string CVC2, 
                    string Mes, 
                    string Ano, 
                    string Portador, 
                    string IATA, 
                    string Distribuidor, 
                    string Concentrador, 
                    string TaxaEmbarque, 
                    string Entrada, 
                    string Pax1, 
                    string Pax2, 
                    string Pax3, 
                    string Pax4, 
                    string Numdoc1, 
                    string Numdoc2, 
                    string Numdoc3, 
                    string Numdoc4, 
                    string ConfTxn, 
                    string AddData) {
            return base.Channel.GetAuthorizedTst(Total, Transacao, Parcelas, Filiacao, NumPedido, Nrcartao, CVC2, Mes, Ano, Portador, IATA, Distribuidor, Concentrador, TaxaEmbarque, Entrada, Pax1, Pax2, Pax3, Pax4, Numdoc1, Numdoc2, Numdoc3, Numdoc4, ConfTxn, AddData);
        }
        
        public System.Xml.XmlNode GetAuthorizedAVSTst(
                    string Total, 
                    string Transacao, 
                    string Parcelas, 
                    string Filiacao, 
                    string NumPedido, 
                    string Nrcartao, 
                    string CVC2, 
                    string Mes, 
                    string Ano, 
                    string Portador, 
                    string CPF, 
                    string Endereco, 
                    string Num1, 
                    string Complemento, 
                    string Cep1, 
                    string Cep2, 
                    string IATA, 
                    string Distribuidor, 
                    string Concentrador, 
                    string TaxaEmbarque, 
                    string Entrada, 
                    string Pax1, 
                    string Pax2, 
                    string Pax3, 
                    string Pax4, 
                    string Numdoc1, 
                    string Numdoc2, 
                    string Numdoc3, 
                    string Numdoc4) {
            return base.Channel.GetAuthorizedAVSTst(Total, Transacao, Parcelas, Filiacao, NumPedido, Nrcartao, CVC2, Mes, Ano, Portador, CPF, Endereco, Num1, Complemento, Cep1, Cep2, IATA, Distribuidor, Concentrador, TaxaEmbarque, Entrada, Pax1, Pax2, Pax3, Pax4, Numdoc1, Numdoc2, Numdoc3, Numdoc4);
        }
    }
}
