//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.OctopusSGAService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Parcela", Namespace="http://schemas.datacontract.org/2004/07/Opus.Octopus.IntegracaoSGA")]
    [System.SerializableAttribute()]
    public partial class Parcela : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BLL.OctopusSGAService.Cheque ChequeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataParcelaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormaPagamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeParcelaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ParcelaPagaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BLL.OctopusSGAService.Promissoria PromissoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorParcelaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BLL.OctopusSGAService.Cheque Cheque {
            get {
                return this.ChequeField;
            }
            set {
                if ((object.ReferenceEquals(this.ChequeField, value) != true)) {
                    this.ChequeField = value;
                    this.RaisePropertyChanged("Cheque");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataParcela {
            get {
                return this.DataParcelaField;
            }
            set {
                if ((this.DataParcelaField.Equals(value) != true)) {
                    this.DataParcelaField = value;
                    this.RaisePropertyChanged("DataParcela");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FormaPagamento {
            get {
                return this.FormaPagamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.FormaPagamentoField, value) != true)) {
                    this.FormaPagamentoField = value;
                    this.RaisePropertyChanged("FormaPagamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeParcela {
            get {
                return this.NomeParcelaField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeParcelaField, value) != true)) {
                    this.NomeParcelaField = value;
                    this.RaisePropertyChanged("NomeParcela");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ParcelaPaga {
            get {
                return this.ParcelaPagaField;
            }
            set {
                if ((this.ParcelaPagaField.Equals(value) != true)) {
                    this.ParcelaPagaField = value;
                    this.RaisePropertyChanged("ParcelaPaga");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BLL.OctopusSGAService.Promissoria Promissoria {
            get {
                return this.PromissoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.PromissoriaField, value) != true)) {
                    this.PromissoriaField = value;
                    this.RaisePropertyChanged("Promissoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorParcela {
            get {
                return this.ValorParcelaField;
            }
            set {
                if ((this.ValorParcelaField.Equals(value) != true)) {
                    this.ValorParcelaField = value;
                    this.RaisePropertyChanged("ValorParcela");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cheque", Namespace="http://schemas.datacontract.org/2004/07/Opus.Octopus.IntegracaoSGA")]
    [System.SerializableAttribute()]
    public partial class Cheque : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BancoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorrentistaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataBomParaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdentificadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroChequeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Agencia {
            get {
                return this.AgenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.AgenciaField, value) != true)) {
                    this.AgenciaField = value;
                    this.RaisePropertyChanged("Agencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Banco {
            get {
                return this.BancoField;
            }
            set {
                if ((object.ReferenceEquals(this.BancoField, value) != true)) {
                    this.BancoField = value;
                    this.RaisePropertyChanged("Banco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CPF {
            get {
                return this.CPFField;
            }
            set {
                if ((object.ReferenceEquals(this.CPFField, value) != true)) {
                    this.CPFField = value;
                    this.RaisePropertyChanged("CPF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Conta {
            get {
                return this.ContaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContaField, value) != true)) {
                    this.ContaField = value;
                    this.RaisePropertyChanged("Conta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correntista {
            get {
                return this.CorrentistaField;
            }
            set {
                if ((object.ReferenceEquals(this.CorrentistaField, value) != true)) {
                    this.CorrentistaField = value;
                    this.RaisePropertyChanged("Correntista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataBomPara {
            get {
                return this.DataBomParaField;
            }
            set {
                if ((this.DataBomParaField.Equals(value) != true)) {
                    this.DataBomParaField = value;
                    this.RaisePropertyChanged("DataBomPara");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Identificador {
            get {
                return this.IdentificadorField;
            }
            set {
                if ((this.IdentificadorField.Equals(value) != true)) {
                    this.IdentificadorField = value;
                    this.RaisePropertyChanged("Identificador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroCheque {
            get {
                return this.NumeroChequeField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroChequeField, value) != true)) {
                    this.NumeroChequeField = value;
                    this.RaisePropertyChanged("NumeroCheque");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Promissoria", Namespace="http://schemas.datacontract.org/2004/07/Opus.Octopus.IntegracaoSGA")]
    [System.SerializableAttribute()]
    public partial class Promissoria : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroPromissoriaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroPromissoria {
            get {
                return this.NumeroPromissoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroPromissoriaField, value) != true)) {
                    this.NumeroPromissoriaField = value;
                    this.RaisePropertyChanged("NumeroPromissoria");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoAcerto", Namespace="http://schemas.datacontract.org/2004/07/Opus.Octopus.IntegracaoSGA")]
    public enum TipoAcerto : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Multa = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Devolucao = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SemAcerto = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OctopusSGAService.ICRM")]
    public interface ICRM {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRM/ObterNaturezasEvento", ReplyAction="http://tempuri.org/ICRM/ObterNaturezasEventoResponse")]
        string[] ObterNaturezasEvento();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRM/IncluirEventoCRM", ReplyAction="http://tempuri.org/ICRM/IncluirEventoCRMResponse")]
        void IncluirEventoCRM(string IDUnidade, string IDUsuario, string CPF, System.DateTime DataEvento, string NaturezaEvento, string DescricaoEvento);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICRMChannel : BLL.OctopusSGAService.ICRM, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CRMClient : System.ServiceModel.ClientBase<BLL.OctopusSGAService.ICRM>, BLL.OctopusSGAService.ICRM {
        
        public CRMClient() {
        }
        
        public CRMClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CRMClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRMClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRMClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] ObterNaturezasEvento() {
            return base.Channel.ObterNaturezasEvento();
        }
        
        public void IncluirEventoCRM(string IDUnidade, string IDUsuario, string CPF, System.DateTime DataEvento, string NaturezaEvento, string DescricaoEvento) {
            base.Channel.IncluirEventoCRM(IDUnidade, IDUsuario, CPF, DataEvento, NaturezaEvento, DescricaoEvento);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OctopusSGAService.IVenda")]
    public interface IVenda {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVenda/RegistrarVenda", ReplyAction="http://tempuri.org/IVenda/RegistrarVendaResponse")]
        void RegistrarVenda(string IDUnidade, string IDUsuario, string CPFAluno, string IDContrato, System.DateTime DataVenda, BLL.OctopusSGAService.Parcela[] CondicaoPagamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVenda/CancelarVenda", ReplyAction="http://tempuri.org/IVenda/CancelarVendaResponse")]
        void CancelarVenda(string IDUnidade, string IDUsuario, string CPFAluno, string IDContrato, string IDContratoTurmaCancelado, BLL.OctopusSGAService.TipoAcerto TipoAcerto, decimal ValorAcerto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVendaChannel : BLL.OctopusSGAService.IVenda, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VendaClient : System.ServiceModel.ClientBase<BLL.OctopusSGAService.IVenda>, BLL.OctopusSGAService.IVenda {
        
        public VendaClient() {
        }
        
        public VendaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VendaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VendaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VendaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void RegistrarVenda(string IDUnidade, string IDUsuario, string CPFAluno, string IDContrato, System.DateTime DataVenda, BLL.OctopusSGAService.Parcela[] CondicaoPagamento) {
            base.Channel.RegistrarVenda(IDUnidade, IDUsuario, CPFAluno, IDContrato, DataVenda, CondicaoPagamento);
        }
        
        public void CancelarVenda(string IDUnidade, string IDUsuario, string CPFAluno, string IDContrato, string IDContratoTurmaCancelado, BLL.OctopusSGAService.TipoAcerto TipoAcerto, decimal ValorAcerto) {
            base.Channel.CancelarVenda(IDUnidade, IDUsuario, CPFAluno, IDContrato, IDContratoTurmaCancelado, TipoAcerto, ValorAcerto);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OctopusSGAService.IRepasse")]
    public interface IRepasse {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepasse/RegistrarRepasseLFG", ReplyAction="http://tempuri.org/IRepasse/RegistrarRepasseLFGResponse")]
        void RegistrarRepasseLFG(string IDUnidade, string IDUsuario, BLL.OctopusSGAService.Cheque[] ChequesAluno, BLL.OctopusSGAService.Cheque[] ChequeUnidade, decimal ValorDeposito);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRepasseChannel : BLL.OctopusSGAService.IRepasse, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RepasseClient : System.ServiceModel.ClientBase<BLL.OctopusSGAService.IRepasse>, BLL.OctopusSGAService.IRepasse {
        
        public RepasseClient() {
        }
        
        public RepasseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RepasseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RepasseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RepasseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void RegistrarRepasseLFG(string IDUnidade, string IDUsuario, BLL.OctopusSGAService.Cheque[] ChequesAluno, BLL.OctopusSGAService.Cheque[] ChequeUnidade, decimal ValorDeposito) {
            base.Channel.RegistrarRepasseLFG(IDUnidade, IDUsuario, ChequesAluno, ChequeUnidade, ValorDeposito);
        }
    }
}
