//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.LoginOctopusService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoginOctopusService.ILoginOctopus")]
    public interface ILoginOctopus {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginOctopus/IntersiteLogin", ReplyAction="http://tempuri.org/ILoginOctopus/IntersiteLoginResponse")]
        string IntersiteLogin(string Username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginOctopus/IntersiteTouch", ReplyAction="http://tempuri.org/ILoginOctopus/IntersiteTouchResponse")]
        void IntersiteTouch(string Hash);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoginOctopusChannel : BLL.LoginOctopusService.ILoginOctopus, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginOctopusClient : System.ServiceModel.ClientBase<BLL.LoginOctopusService.ILoginOctopus>, BLL.LoginOctopusService.ILoginOctopus {
        
        public LoginOctopusClient() {
        }
        
        public LoginOctopusClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginOctopusClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginOctopusClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginOctopusClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string IntersiteLogin(string Username) {
            return base.Channel.IntersiteLogin(Username);
        }
        
        public void IntersiteTouch(string Hash) {
            base.Channel.IntersiteTouch(Hash);
        }
    }
}
