//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.WsEnemMais {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:WSDL", ConfigurationName="WsEnemMais.ServerPortType")]
    public interface ServerPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServerAction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="InsertUpdateGradeReturn")]
        int InsertUpdateGrade(object shortname, object username, object assignment, object grade);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServerAction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="deleteUserReturn")]
        int deleteUser(object username);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServerAction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="desenrolUserCourseReturn")]
        int desenrolUserCourse(object username1, object shortname);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServerAction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="enrolUserCourseReturn")]
        int enrolUserCourse(object username1, object shortname1, object role, object groupname);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServerAction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="removeFromGroupReturn")]
        int removeFromGroup(object username1, object shortname1);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServerAction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="finalGradeReturn")]
        int finalGrade(object user, object course);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServerAction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="insertCourseReturn")]
        int insertCourse(object @params);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServerAction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="insertUserReturn")]
        int insertUser(object username1, object password, object firstname, object lastname, object confirmed, object email, object idnumber, object lang, object change);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServerAction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="insertUserReturn")]
        int insertUserArray(object params1);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServerAction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="restoreUserReturn")]
        int restoreUser(object username1);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServerAction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="searchCourseReturn")]
        object searchCourse(object shortname1, object @return);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServerAction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getContextReturn")]
        object getContext(object id1, object @return);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServerAction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="searchEnrolmentReturn")]
        object searchEnrolment(object shortname1, object role1);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServerAction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="searchRoleReturn")]
        object searchRole(object role1);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServerAction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="searchUserReturn")]
        object searchUser(object username1);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServerPortTypeChannel : BLL.WsEnemMais.ServerPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServerPortTypeClient : System.ServiceModel.ClientBase<BLL.WsEnemMais.ServerPortType>, BLL.WsEnemMais.ServerPortType {
        
        public ServerPortTypeClient() {
        }
        
        public ServerPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServerPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int InsertUpdateGrade(object shortname, object username, object assignment, object grade) {
            return base.Channel.InsertUpdateGrade(shortname, username, assignment, grade);
        }
        
        public int deleteUser(object username) {
            return base.Channel.deleteUser(username);
        }
        
        public int desenrolUserCourse(object username1, object shortname) {
            return base.Channel.desenrolUserCourse(username1, shortname);
        }
        
        public int enrolUserCourse(object username1, object shortname1, object role, object groupname) {
            return base.Channel.enrolUserCourse(username1, shortname1, role, groupname);
        }
        
        public int removeFromGroup(object username1, object shortname1) {
            return base.Channel.removeFromGroup(username1, shortname1);
        }
        
        public int finalGrade(object user, object course) {
            return base.Channel.finalGrade(user, course);
        }
        
        public int insertCourse(object @params) {
            return base.Channel.insertCourse(@params);
        }
        
        public int insertUser(object username1, object password, object firstname, object lastname, object confirmed, object email, object idnumber, object lang, object change) {
            return base.Channel.insertUser(username1, password, firstname, lastname, confirmed, email, idnumber, lang, change);
        }
        
        public int insertUserArray(object params1) {
            return base.Channel.insertUserArray(params1);
        }
        
        public int restoreUser(object username1) {
            return base.Channel.restoreUser(username1);
        }
        
        public object searchCourse(object shortname1, object @return) {
            return base.Channel.searchCourse(shortname1, @return);
        }
        
        public object getContext(object id1, object @return) {
            return base.Channel.getContext(id1, @return);
        }
        
        public object searchEnrolment(object shortname1, object role1) {
            return base.Channel.searchEnrolment(shortname1, role1);
        }
        
        public object searchRole(object role1) {
            return base.Channel.searchRole(role1);
        }
        
        public object searchUser(object username1) {
            return base.Channel.searchUser(username1);
        }
    }
}
